services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - certbot_certs:/etc/letsencrypt
    - certbot_www:/var/www/certbot
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    container_name: tequicalli-certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  db:
    image: postgres:14
    container_name: tequicalli-db
    env_file:
    - .env
    volumes:
    - db_data:/var/lib/postgresql/data

volumes: 
  certbot_certs:
  certbot_www:
  db_data: