"""Add image_file column to Client model

Revision ID: 235e9a8e02e1
Revises: 
Create Date: 2025-04-15 06:59:10.891982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235e9a8e02e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
